version: 2.0.{build}
image: Visual Studio 2017
configuration: Release
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
init:
  - tzutil /s "W. Australia Standard Time"
clone_folder: c:\projects\ExtensionMinder
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - dotnet restore
build:
  project: ExtensionMinder.sln
  parallel: false
  verbosity: normal
  publish_nuget: true
after_build:
  - dotnet pack "c:\projects\ExtensionMinder\ExtensionMinder\ExtensionMinder.csproj" -Properties "Configuration=Release;Platform=AnyCPU"  -IncludeReferencedProjects
cache:
  - packages -> **\packages.config
artifacts:
- path: '*.nupkg'
  name: extensionminder
deploy:
- provider: NuGet
  api_key:
    secure: YxZTLAgoxyNdCF2wqeGHQnRrWdNy3ZpwoVtN6Oe4E7U16sXFPNvn77ZsRnUEBzzG
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: extensionminder
