version: {build}
image: Visual Studio 2017
configuration: Release
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
init:
  - tzutil /s "W. Australia Standard Time"
clone_folder: c:\projects\ExtensionMinder
before_build:
  - dotnet restore
build:
  project: ExtensionMinder.sln
  parallel: false
  verbosity: normal
  publish_nuget: true
after_build:
  - cmd: dotnet pack "c:\projects\ExtensionMinder\ExtensionMinder\ExtensionMinder.csproj" --include-symbols --configuration %CONFIGURATION% --no-build --output ..\nupkgs /p:PackageVersion=%APPVEYOR_BUILD_VERSION%
artifacts:
  - path: '**\*.nupkg' # find all NuGet packages recursively

  
