version: 2.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
init:
  - tzutil /s "W. Australia Standard Time"
configuration: Release
clone_folder: c:\projects\ExtensionMinder
before_build:
  - dotnet restore
build:
  project: ExtensionMinder.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
artifacts:
- path: extensionminder.nuspec
  name: extensionminder
deploy:
- provider: NuGet
  server: https://nugetserver.com/nuget/feed
  api_key:
    secure: rlvBKgUdqBrIgLW8GJeI74rV/W20v/KaMeQawgKLsU1hdJAqo9vEoOWnxfd9Amru
  artifact: ExtensionMinder