# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- releases/*
# variables:
# - group: AUAZE-CORP-DEV-CPS
pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps
steps:
- powershell: |
    Write-Host "Code retreived"
  displayName: 'Code retrieved'
