name: build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      src: ${{ github.workspace }}/ExtensionMinder
      tests: ${{ github.workspace }}/ExtensionMinder.Tests

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: AddSource
      env: 
        WHO_TO_TRUST: ${{ secrets.EXTENSIONMINDERTRUST }} # EXTENSIONMINDERTRUST is a repo level secret containing a PAT with only read:packages access
      run: dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ env.WHO_TO_TRUST }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/chrismckelt/index.json"
    - name: Build
      run: dotnet build --configuration Debug
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Build2
      run: dotnet build --configuration Release
    - name: Package solution
      run: dotnet pack --configuration Release
    - name: Publish GitHub
      run: dotnet nuget push "ExtensionMinder/bin/Release/ExtensionMinder.*.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate #GITHUB_TOKEN has write:packages access by default, so we are good
    - name: Publish Nuget
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGETAPIKEY}} --source "nuget" --skip-duplicate
    
