name: build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      src: ${{ github.workspace }}/ExtensionMinder
      tests: ${{ github.workspace }}/ExtensionMinder.Tests

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Build
      run: dotnet build --configuration Debug
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Package solution
      run: dotnet pack --configuration Debug
    - name: Publish package
      run: dotnet nuget push "ExtensionMinder/bin/Debug/ExtensionMinder.*.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate #GITHUB_TOKEN has write:packages access by default, so we are good